version: '3'

services:
  rublevka_frontend_prod:
    image: rublevka_frontend_prod
    container_name: rublevka_frontend_prod
    restart: always
    build:
      context: .
      args:
        - APP=rublevka
        - HOST=rublevka.ru
        - APP_ENV
        - REACT_APP_SENTRY_DSN
        - REACT_APP_FACEBOOK_PIXEL_ID
        - REACT_APP_TARGETIX_PIXEL_ID
        - REACT_APP_ROISTAT_ID
        - REACT_APP_GOOGLE_ANALYTICS_ID
        - REACT_APP_YANDEX_METRIKA_ID
        - REACT_APP_UIS_ID
        - BUILD_ID
    networks:
      master_network:
        aliases:
          - rublevka_frontend_prod

  riga_frontend_prod:
    image: riga_frontend_prod
    container_name: riga_frontend_prod
    restart: always
    build:
      context: .
      args:
        - APP=riga
        - HOST=riga.ru
        - APP_ENV
        - REACT_APP_SENTRY_DSN
        - REACT_APP_FACEBOOK_PIXEL_ID
        - REACT_APP_TARGETIX_PIXEL_ID
        - REACT_APP_ROISTAT_ID
        - REACT_APP_GOOGLE_ANALYTICS_ID
        - REACT_APP_YANDEX_METRIKA_ID
        - REACT_APP_UIS_ID
        - BUILD_ID
    networks:
      master_network:
        aliases:
          - riga_frontend_prod

networks:
  master_network:
    external: true
